import type { ComplexityReport, DeveloperProfile } from "@code-insight/core";
import type { App, KnownBlock } from "@slack/bolt";

export interface MessageContext {
	channelId: string;
	messageTs: string;
	userId: string;
	text: string;
}

export class SlackAdapter {
	private readonly botToken: string;

	constructor(
		private readonly app: App,
		botToken: string,
	) {
		this.botToken = botToken;
	}

	async addReaction(
		channel: string,
		timestamp: string,
		emoji: string,
	): Promise<void> {
		await this.app.client.reactions.add({
			token: this.botToken,
			channel,
			timestamp,
			name: emoji,
		});
	}

	async removeReaction(
		channel: string,
		timestamp: string,
		emoji: string,
	): Promise<void> {
		try {
			await this.app.client.reactions.remove({
				token: this.botToken,
				channel,
				timestamp,
				name: emoji,
			});
		} catch {
			// Ignore if reaction doesn't exist
		}
	}

	async sendReport(
		context: MessageContext,
		report: ComplexityReport,
		recommendedOwner?: DeveloperProfile,
	): Promise<void> {
		const blocks = this.buildReportBlocks(report, recommendedOwner);

		await this.app.client.chat.postMessage({
			token: this.botToken,
			channel: context.channelId,
			thread_ts: context.messageTs,
			blocks,
			text: `Complexity Analysis Report: ${report.feasibility} feasibility, ${report.complexity} complexity`,
		});
	}

	async sendThreadMessage(
		channel: string,
		threadTs: string,
		text: string,
	): Promise<void> {
		await this.app.client.chat.postMessage({
			token: this.botToken,
			channel,
			thread_ts: threadTs,
			text,
		});
	}

	private buildReportBlocks(
		report: ComplexityReport,
		owner?: DeveloperProfile,
	): KnownBlock[] {
		const feasibilityEmoji =
			report.feasibility === "Possible"
				? "✅"
				: report.feasibility === "Difficult"
					? "⚠️"
					: "🚫";

		const complexityEmoji =
			report.complexity === "Low"
				? "🟢"
				: report.complexity === "Medium"
					? "🟡"
					: "🔴";

		const blocks: KnownBlock[] = [
			{
				type: "header",
				text: {
					type: "plain_text",
					text: "📊 Complexity Analysis Report",
					emoji: true,
				},
			},
			{
				type: "section",
				fields: [
					{
						type: "mrkdwn",
						text: `*Feasibility:*\n${feasibilityEmoji} ${report.feasibility}`,
					},
					{
						type: "mrkdwn",
						text: `*Modification Complexity:*\n${complexityEmoji} ${report.complexity}`,
					},
				],
			},
			{
				type: "section",
				text: {
					type: "mrkdwn",
					text: `*Reason:* ${report.feasibilityReason || report.summary}`,
				},
			},
			{ type: "divider" },
		];

		if (report.riskFactors.length > 0) {
			const riskText = report.riskFactors
				.map((r) => {
					const emoji =
						r.severity === "High"
							? "🔴"
							: r.severity === "Medium"
								? "🟡"
								: "🟢";
					return `${emoji} ${r.description}`;
				})
				.join("\n");

			blocks.push({
				type: "section",
				text: { type: "mrkdwn", text: `*⚠️ Risk Factors:*\n${riskText}` },
			});
		}

		if (report.targetFiles.length > 0) {
			const filesText = report.targetFiles
				.map((f) => `• \`[${f.repo}] ${f.path}\``)
				.join("\n");

			blocks.push({
				type: "section",
				text: {
					type: "mrkdwn",
					text: `*📁 Major Expected Files to Modify:*\n${filesText}`,
				},
			});
		}

		if (owner) {
			blocks.push(
				{ type: "divider" },
				{
					type: "section",
					text: {
						type: "mrkdwn",
						text: `💡 *Recommended Owner:* We recommend discussing this with *${owner.slackUserId ? `<@${owner.slackUserId}>` : owner.name}* who recently modified ${owner.recentFiles.map((f) => `\`${f}\``).join(", ")}.`,
					},
				},
				{
					type: "actions",
					elements: [
						{
							type: "button",
							text: {
								type: "plain_text",
								text: `📩 Request Review from ${owner.name}`,
								emoji: true,
							},
							style: "primary",
							action_id: "request_review_action",
							value: JSON.stringify({
								githubUsername: owner.githubUsername,
								slackUserId: owner.slackUserId,
								name: owner.name,
							}),
						},
					],
				},
			);
		}

		blocks.push({
			type: "context",
			elements: [
				{
					type: "mrkdwn",
					text: "🤖 _Generated by Code-Insight | This is an AI-assisted analysis. Please verify with the recommended owner._",
				},
			],
		});

		return blocks;
	}
}
